2022-05-05 19:49:41,134 [INFO] uvicorn.error: Started server process [68115]
2022-05-05 19:49:41,134 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 19:49:41,134 [INFO] uvicorn.error: Application startup complete.
2022-05-05 19:49:41,135 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 19:50:30,409 [INFO] uvicorn.error: Shutting down
2022-05-05 19:50:30,512 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 19:50:30,513 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 19:50:30,513 [INFO] uvicorn.error: Finished server process [68115]
2022-05-05 20:06:45,503 [INFO] uvicorn.error: Started server process [68391]
2022-05-05 20:06:45,504 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:06:45,504 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:06:45,505 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:08:14,419 [ERROR] uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/evavi/fourthbrain/week4-dock/hw1/./main.py", line 45, in predict
    result = sa_model(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/transformers/pipelines/text_classification.py", line 125, in __call__
    result = super().__call__(*args, **kwargs)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1026, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1032, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/transformers/pipelines/text_classification.py", line 134, in preprocess
    return self.tokenizer(inputs, return_tensors=return_tensors, **tokenizer_kwargs)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2429, in __call__
    raise ValueError(
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
2022-05-05 20:12:18,287 [INFO] uvicorn.error: Shutting down
2022-05-05 20:12:18,388 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:12:18,389 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:12:18,389 [INFO] uvicorn.error: Finished server process [68391]
2022-05-05 20:12:29,414 [INFO] uvicorn.error: Started server process [68444]
2022-05-05 20:12:29,415 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:12:29,417 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:12:29,418 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:13:36,083 [ERROR] uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/evavi/fourthbrain/week4-dock/hw1/./main.py", line 44, in predict
    result = sa_model(request['in_text'])
TypeError: 'SentimentRequest' object is not subscriptable
2022-05-05 20:17:19,981 [INFO] uvicorn.error: Shutting down
2022-05-05 20:17:20,087 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:17:20,088 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:17:20,088 [INFO] uvicorn.error: Finished server process [68444]
2022-05-05 20:17:27,728 [INFO] uvicorn.error: Started server process [68472]
2022-05-05 20:17:27,728 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:17:27,728 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:17:27,729 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:19:48,294 [INFO] uvicorn.error: Shutting down
2022-05-05 20:19:48,395 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:19:48,396 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:19:48,396 [INFO] uvicorn.error: Finished server process [68472]
2022-05-05 20:19:57,163 [INFO] uvicorn.error: Started server process [68482]
2022-05-05 20:19:57,163 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:19:57,163 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:19:57,164 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:20:03,492 [ERROR] uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/evavi/fourthbrain/week4-dock/hw1/./main.py", line 44, in predict
    sentiment=result['label'],
TypeError: list indices must be integers or slices, not str
2022-05-05 20:20:56,500 [INFO] uvicorn.error: Shutting down
2022-05-05 20:20:56,604 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:20:56,605 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:20:56,605 [INFO] uvicorn.error: Finished server process [68482]
2022-05-05 20:21:12,161 [INFO] uvicorn.error: Started server process [68489]
2022-05-05 20:21:12,161 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:21:12,161 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:21:12,162 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:21:16,820 [ERROR] uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/evavi/fourthbrain/week4-dock/hw1/./main.py", line 44, in predict
    sentiment=result.label,
AttributeError: 'list' object has no attribute 'label'
2022-05-05 20:22:15,007 [INFO] uvicorn.error: Shutting down
2022-05-05 20:22:15,110 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:22:15,111 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:22:15,111 [INFO] uvicorn.error: Finished server process [68489]
2022-05-05 20:22:21,606 [INFO] uvicorn.error: Started server process [68494]
2022-05-05 20:22:21,606 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:22:21,606 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:22:21,607 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:22:26,494 [ERROR] uvicorn.error: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/evavi/opt/anaconda3/envs/aws_fastapi/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/evavi/fourthbrain/week4-dock/hw1/./main.py", line 46, in predict
    score=result[1])
IndexError: list index out of range
2022-05-05 20:23:45,030 [INFO] uvicorn.error: Shutting down
2022-05-05 20:23:45,136 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:23:45,136 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:23:45,136 [INFO] uvicorn.error: Finished server process [68494]
2022-05-05 20:23:51,666 [INFO] uvicorn.error: Started server process [68498]
2022-05-05 20:23:51,666 [INFO] uvicorn.error: Waiting for application startup.
2022-05-05 20:23:51,666 [INFO] uvicorn.error: Application startup complete.
2022-05-05 20:23:51,667 [INFO] uvicorn.error: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2022-05-05 20:24:17,868 [INFO] uvicorn.error: Shutting down
2022-05-05 20:24:17,974 [INFO] uvicorn.error: Waiting for application shutdown.
2022-05-05 20:24:17,975 [INFO] uvicorn.error: Application shutdown complete.
2022-05-05 20:24:17,975 [INFO] uvicorn.error: Finished server process [68498]
